### ISSUE TITLE
Tests are failed on ECL and CLisp

### ISSUE THREAD

**Issue by catap** [hraban/metacopy#2]
ECL:
```
:info:build ;;; Loading #P"/opt/local/lib/ecl-21.2.1/asdf.fas"
:info:build An error occurred during initialization:
:info:build The assertion (<= (LENGTH METACOPY-SYSTEM::PATHS) 1) failed.
```

Clisp:
```
:info:build #P"/opt/local/lib/clisp-2.49.93+/dynmod/asdf.lisp"
:info:build (*DEFAULT-PATHNAME-DEFAULTS*
:info:build  #P"/opt/local/var/macports/build/_Users_catap_src_macports-ports_lisp_cl-metacopy/cl-metacopy/work/build/system/"
:info:build  #P"/opt/local/share/common-lisp/system/")
:info:build WARNING: Adding method
:info:build          #<STANDARD-METHOD (#<STANDARD-CLASS TEST-OP> (EQL #<SYSTEM 
:info:build          "metacopy/test">))> to an already called generic function
:info:build          #<STANDARD-GENERIC-FUNCTION PERFORM>
:info:build WARNING: Adding method
:info:build          #<STANDARD-METHOD :AROUND (#<STANDARD-CLASS OPERATION> #<STANDARD-CLASS METACOPY-FILE-WITH-CONTEXTL>)>
:info:build          to an already called generic function
:info:build          #<STANDARD-GENERIC-FUNCTION OUTPUT-FILES>
:info:build *** - (<= (LENGTH METACOPY-SYSTEM::PATHS) 1) must evaluate to a non-NIL value.
```

**Comment by gwkkwg** [comment]
Thanks. Sadly (or not), I no longer Lisp. If you’d like to take over, please let me know how I can facilitate.

**Comment by hraban** [comment]
@catap I had a completely unrelated problem when running the tests with ECL. After I fixed that, I couldn't reproduce your original bug. It really has nothing to do with it, so I'm surprised that A) you don't run into my (old) issue, and B) I don't run into yours.

Can you show me exactly how you run the tests? For now, I cannot repro.

**Comment by catap** [comment]
@hraban I've encountered this issue when I worked on creating a port file for MacPorts.

Tests runs `asdf:test-op` on all `.asd` files in the packages. Here the command was (for clisp) like:
```
:info:build ;;; Loading #P"/opt/local/lib/ecl-21.2.1/asdf.fas"
:info:build An error occurred during initialization:
:info:build The assertion (<= (LENGTH METACOPY-SYSTEM::PATHS) 1) failed.
:info:build Command failed: /opt/local/bin/ecl -q --eval '(require "asdf")' --eval '(setf asdf:*central-registry* (list* (quote *default-pathname-defaults*) #p"/opt/local/var/macports/build/_Users_catap_src_macports-ports_lisp_cl-metacopy/cl-metacopy/work/build/system/" #p"/opt/local/share/common-lisp/system/" asdf:*central-registry*))' --eval '(asdf:operate (quote asdf:build-op) (quote metacopy-with-contextl))' 2>&1
```

I've tried 18dad68bf11332e6a339ccf92ee39a304cb0b6c2 as local root an it doesn't fix an issue.

**Comment by hraban** [comment]
Thanks I can repro now. I'm still debugging some weird ASDF wizardry being pulled off in the `contextl` part of this file, but I did find this in the contextl README:

> Warning: ContextL currently doesn't work on Embeddable Common Lisp (as of ECL 16.1.2, and already since a couple of versions before). Currently investigating what the issue is. Please stay tuned.

- https://github.com/pcostanza/contextl

That rules out using the entire contextl part with ECL, probably. I don't think the error you're seeing is related to that; it's trying to help ASDF manage output files for some reason, and it expects a 1<->1 relationship between .lisp and .fasl files, which breaks for ECL (.fas + .o for every .lisp).

I'll keep looking into what exactly is going on, but I will say that given that note in the README, it doesn't look like this will ever actually help for ECL. Maybe clisp is different.

**Comment by hraban** [comment]
@catap #4 should fix it, can you give it a shot?
